server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:

        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**,/api/v1/auth/**
          filters:
            - StripPrefix=2

        - id: video-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/videos/**
          filters:
            - StripPrefix=2

        - id: streaming-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/stream/**
          filters:
            - StripPrefix=2
logging:
  level:
    org.springframework.security: DEBUG
